# Generated by Django 5.0.8 on 2024-08-13 04:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('carImg', models.ImageField(upload_to='cars/')),
                ('registeredDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('carType', models.CharField(choices=[('SUV', 'SUV'), ('sedan', 'sedan')], max_length=15)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingDate', models.DateField(default=django.utils.timezone.now)),
                ('carBooking', models.ManyToManyField(related_name='bookings', to='me.car')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('registrationDate', models.DateField(default=django.utils.timezone.now)),
                ('relation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='me.car')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('comment', models.TextField()),
                ('reviewDate', models.DateField(default=django.utils.timezone.now)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='me.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
