# Generated by Django 5.0.8 on 2024-08-13 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='userBooking',
            field=models.ManyToManyField(related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
