# Generated by Django 5.0.8 on 2024-08-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payAmount',
            field=models.IntegerField(),
        ),
    ]
