# Generated by Django 5.0.8 on 2024-08-15 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_alter_payment_payamount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
