# Generated by Django 5.0.8 on 2024-08-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0005_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registraion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('firstName', models.CharField(blank=True, max_length=30)),
                ('lastName', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
