# Generated by Django 5.0.8 on 2024-08-15 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0006_registraion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registraion',
        ),
    ]
